version: '3.8'
services:
  "${APP_NAME}":
    container_name: "${APP_NAME}"
    build: ./
    ports:
      - "${DOCKER_PORT}:${HOST_PORT}"
    tty: true
    volumes:
      - ./app:/usr/src/app
    environment:
      PORT: "${HOST_PORT}"
